name = "Hackcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "346a8878a548ae416c5b704abf81cfe6f54a1fae248bb0e8a03c778cf11c8520"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
