name = "Hackcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87fa3f3620b355bc40ba7f1e29db2a09b0241d0ae140435bfe4a5aa920ba460a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
