name = "Hackcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c29c4cccc369f0288236db0f8ff2d2dbeca5ed1a2011f4b02b8bc82d18addb8e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
